# -----------Plugin made by abcalvin from WolfCFR--------------
Prevent:
  Pickup: true
  Craft: true
  Interaction: true
  Break: true
  Place: true
  Confiscate: true
  Click: true
Ban Message: This item is banned!
Confiscate Message: This item is banned and is confiscated! 
Blacklist:
Blacklist Placement:
Blacklist Break:
Blacklist Crafting:
Blacklist Interaction:
Blacklist Pickup:
Blacklist Click: